### ISSUE TITLE
Opconversion Failure for gemma-7b_INT4

### ISSUE THREAD

**Issue by saivivekseeram1** [openvinotoolkit/openvino_notebooks#1876]
here i'm attaching the screenshots.
![gemma-7b-booleanerror](https://github.com/openvinotoolkit/openvino_notebooks/assets/92068535/9ca6e1a0-c968-419e-a246-d5c27565b6d5)
![gemmA7B-filesdownloadsucessfully](https://github.com/openvinotoolkit/openvino_notebooks/assets/92068535/34770e67-f34d-47ef-86a5-963910deb27a)

**Comment by eaidova** [comment]
@saivivekseeram1 hello, please make sure that you executed cell with installing requirements in notebook before running model conversion. This issue required to use openvino-nightly package for resolving, while error what you see appears in openvino 2024.0.0

**Comment by saivivekseeram1** [comment]
okay Thank you @eaidova , it ran successfully. while conversating with the dialogue , it's throwing an error in the middle of dialogue box. 

1. i gave temperature as 1.0 and 0.1 , but still the issue was same
![Screenshot 2024-04-02 232138](https://github.com/openvinotoolkit/openvino_notebooks/assets/92068535/be38fc10-5bac-4e9d-ae09-6f84924866d2)
![Screenshot 2024-04-02 232158](https://github.com/openvinotoolkit/openvino_notebooks/assets/92068535/4b9c7536-598f-4800-84e1-587758170956)

i'm attaching here the doument.

Exception in thread Thread-22 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
Exception in thread Thread-24 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    yield
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    resp = self._pool.handle_request(req)
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    raise exc from None
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    response = connection.handle_request(
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    raise exc
...
    self.gen.throw(typ, value, traceback)
  File "c:\Users\Local_Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out
