### ISSUE TITLE
Custom AI Assistant recipe fails to convert and optimize model

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/openvino_notebooks#2270]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

Custom AI Assistant recipe at https://github.com/openvinotoolkit/openvino_notebooks/tree/recipes/recipes/custom_ai_assistant fails while running `python convert_and_optimize_asr.py --precision int8`

 **Expected behavior**

Command to convert and optimize should work

**Screenshots**

```
(venv) root@vscode-service-prod-1-4l6qq:/workspace/custom_ai_assistant# python convert_and_optimize_asr.py --precision int8
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.29k/2.29k [00:00<00:00, 11.6MB/s]
Framework not specified. Using pt to export the model.
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.51G/1.51G [00:13<00:00, 112MB/s]
generation_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.62k/3.62k [00:00<00:00, 22.0MB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 283k/283k [00:00<00:00, 463kB/s]
vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 836k/836k [00:00<00:00, 1.03MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.48M/2.48M [00:00<00:00, 4.02MB/s]
merges.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 494k/494k [00:00<00:00, 29.2MB/s]
normalizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.7k/52.7k [00:00<00:00, 256kB/s]
added_tokens.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.6k/34.6k [00:00<00:00, 106MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.08k/2.08k [00:00<00:00, 9.40MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
preprocessor_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 339/339 [00:00<00:00, 2.09MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 448, 'suppress_tokens': [1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50360, 50361, 50362], 'begin_suppress_tokens': [220, 50257]}
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using framework PyTorch: 2.4.0+cu121
Overriding 1 configuration item(s)
        - use_cache -> False
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py:1162: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_features.shape[-1] != expected_seq_length:
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py:341: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py:380: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
Using framework PyTorch: 2.4.0+cu121
Overriding 1 configuration item(s)
        - use_cache -> True
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py:86: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1 or self.sliding_window is not None:
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py:162: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_key_values_length > 0:
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py:348: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, tgt_len, src_len):
Using framework PyTorch: 2.4.0+cu121
Overriding 1 configuration item(s)
        - use_cache -> True
/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py:303: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  and past_key_value[0].shape[2] == key_value_states.shape[1]
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 448, 'suppress_tokens': [1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50360, 50361, 50362], 'begin_suppress_tokens': [220, 50257]}
INFO:nncf:Statistics of the bitwidth distribution:
┍━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┑
│   Num bits (N) │ % all parameters (layers)   │ % ratio-defining parameters (layers)   │
┝━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┥
│              8 │ 100% (194 / 194)            │ 100% (194 / 194)                       │
┕━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┙
Applying Weight Compression ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/194 • 0:00:00 • -:--:--
Traceback (most recent call last):
  File "/workspace/custom_ai_assistant/convert_and_optimize_asr.py", line 56, in <module>
    convert_asr_model(args.asr_model_type, args.precision, Path(args.model_dir))
  File "/workspace/custom_ai_assistant/convert_and_optimize_asr.py", line 31, in convert_asr_model
    ov_model = OVModelForSpeechSeq2Seq.from_pretrained(model_name, export=True, compile=False, load_in_8bit=True)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/modeling_base.py", line 420, in from_pretrained
    return from_pretrained_method(
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/modeling_base_seq2seq.py", line 337, in _from_transformers
    return cls._from_pretrained(
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/modeling_seq2seq.py", line 897, in _from_pretrained
    return _OVModelForWhisper._from_pretrained(model_id, config, **kwargs)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/modeling_seq2seq.py", line 916, in _from_pretrained
    return super(OVModelForSpeechSeq2Seq, cls)._from_pretrained(model_id, config, **kwargs)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/modeling_base_seq2seq.py", line 193, in _from_pretrained
    encoder = cls.load_model(os.path.join(model_id, encoder_file_name), quantization_config)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/modeling_base.py", line 147, in load_model
    model = _weight_only_quantization(model, quantization_config)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/optimum/intel/openvino/quantization.py", line 823, in _weight_only_quantization
    return nncf.compress_weights(
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/nncf/quantization/quantize_model.py", line 503, in compress_weights
    return compression_weights_impl(
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/nncf/openvino/quantization/quantize_model.py", line 434, in compress_weights_impl
    return compression_algorithm.apply(model, graph, dataset=dataset)
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/nncf/quantization/algorithms/weight_compression/algorithm.py", line 398, in apply
    transformed_model = self._backend_entity.transform_model(
  File "/workspace/custom_ai_assistant/venv/lib/python3.10/site-packages/nncf/quantization/algorithms/weight_compression/openvino_backend.py", line 177, in transform_model
    converted_const = opset.convert(compressed_const, ov.Type.f16)
  File "/opt/intel/openvino_2023.2.0.13157/python/openvino/runtime/utils/decorators.py", line 23, in wrapper
    node = node_factory_function(*args, **kwargs)
  File "/opt/intel/openvino_2023.2.0.13157/python/openvino/runtime/opset1/ops.py", line 366, in convert
    destination_type = get_element_type_str(destination_type)
  File "/opt/intel/openvino_2023.2.0.13157/python/openvino/runtime/utils/types.py", line 95, in get_element_type_str
    raise OVTypeError("Unidentified data type %s", data_type)
openvino.runtime.exceptions.OVTypeError: ('Unidentified data type %s', <Type: 'float16'>)
```

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

Followed installation instructions on the README.md file in the folder:

```
python3 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip 
pip install -r requirements.txt
```

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

I only have the sources from the custom_ai_assistant. if check_install is also relevant to the recipes, please let me know

**Additional context**

**Comment by dnoliver** [comment]
Now that I see the logs, looks like it's taking an old installation of openvino in /opt/intel/openvino

**Comment by dnoliver** [comment]
My bad! was an environment problem!

after doing:

```
unset InferenceEngine_DIR
unset OpenVINO_DIR
unset INTEL_OPENVINO_DIR
unset PYTHONPATH
unset LD_LIBRARY_PATH
unset ngraph_DIR
```

This took the right version of openvino, and script was succesfull
